# pydbfntx — Pure-Python reader for Clipper/Harbour DBF+NTX files
# Copyright (C) 2026  Vailton Renato  vailtom <at> gmail <dot> com
# https://github.com/vailtom/pydbfntx
#
# Implemented with reference to the Harbour Project's open-source implementation
# of the NTX format and DBF/NTX behaviour. Harbour: https://github.com/harbour/core
#   include/hbrddntx.h  —  NTX header structure and constants
#   src/rdd/dbfntx/dbfntx1.c  —  B-tree seek, key encoding, page layout
# This is an independent Python implementation.
# Thanks to the Harbour contributors for documenting and implementing these formats.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.
"""
test_clipper_compat.py
======================
Compatibility test suite against a real Clipper 5/Harbour-generated DBF+NTX.

The files are expected at:
    <repo_root>/gera_dbf/PESSOAS.dbf
    <repo_root>/gera_dbf/NOME_IDX.ntx
    <repo_root>/gera_dbf/NASC_IDX.ntx
    <repo_root>/gera_dbf/IDADE_IDX.ntx
    <repo_root>/gera_dbf/CASADO_IDX.ntx

Generated by GERA_DBF.PRG (Harbour/Clipper 5.0) with 1000 records.
The expected values below come directly from resultado_teste.txt produced
by the same Clipper program.

Structure:
    NOME      (C,30)   name
    SOBRENOME (C,40)   surname
    IDADE     (N,3,0)  age  (18..87)
    DT_NASC   (D,8)    birth date
    CASADO    (L,1)    married (T/F)

Indexes:
    NOME_IDX   key = NOME + STR(IDADE,3) + IF(CASADO,"S","N")  [C, 34]
    NASC_IDX   key = DTOS(DT_NASC)                              [C,  8]
    IDADE_IDX  key = STR(IDADE,3)                               [C,  3]
    CASADO_IDX key = IF(CASADO,"S","N")                         [C,  1]

Notes on key encoding
---------------------
All four indexes use CHARACTER keys (the expressions evaluate to strings).
ntx_num_to_str() is NOT used here — the numeric sort order comes from the
fact that STR(N,width) left-pads with spaces, so the string ordering of
" 18" < " 30" < " 65" mirrors numeric ordering.

For CASADO_IDX the keys are 'N' (solteiro) and 'S' (casado).  ASCII
ordering puts 'N' (78) before 'S' (83), matching Clipper's result.
"""

from __future__ import annotations

from datetime import date
from pathlib import Path
from collections import Counter

import pytest

from pydbfntx import DBFNTXTable, NTXReader, DBFReader

# ---------------------------------------------------------------------------
# Fixtures / paths
# ---------------------------------------------------------------------------

GERA_DBF = Path(__file__).parent.parent / "gera_dbf"

pessoas_available = pytest.mark.skipif(
    not (GERA_DBF / "PESSOAS.dbf").exists(),
    reason="gera_dbf test data not present (run GERA_DBF.EXE first)",
)


@pytest.fixture(scope="module")
def t():
    """DBFNTXTable with all four indexes open."""
    tbl = DBFNTXTable(
        str(GERA_DBF / "PESSOAS.dbf"),
        [
            str(GERA_DBF / "NOME_IDX.ntx"),
            str(GERA_DBF / "NASC_IDX.ntx"),
            str(GERA_DBF / "IDADE_IDX.ntx"),
            str(GERA_DBF / "CASADO_IDX.ntx"),
        ],
        encoding="cp850",
    )
    yield tbl
    tbl.close()


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _nome(rec):
    return rec["NOME"].strip()


def _sob(rec):
    return rec["SOBRENOME"].strip()


# ===========================================================================
# BASIC SANITY
# ===========================================================================

@pessoas_available
def test_num_records(t):
    assert t.dbf.num_records == 1000


@pessoas_available
def test_no_deleted_records(t):
    t.set_order(0)
    for rec in t:
        assert rec["_deleted"] is False


@pessoas_available
def test_all_ages_in_range(t):
    t.set_order(0)
    for rec in t:
        assert 18 <= rec["IDADE"] <= 87


@pessoas_available
def test_all_birth_dates_present(t):
    t.set_order(0)
    for rec in t:
        assert isinstance(rec["DT_NASC"], date)


# ===========================================================================
# TESTE 1 – NOME_IDX  (composite: NOME + STR(IDADE,3) + IF(CASADO,"S","N"))
# ===========================================================================

@pessoas_available
def test_nome_idx_key_expr(t):
    t.set_order("nome_idx")
    assert t._active_ntx.key_expr == 'NOME + STR(IDADE,3) + IF(CASADO,"S","N")'
    assert t._active_ntx.key_size == 34


@pessoas_available
def test_nome_idx_total_count(t):
    t.set_order("nome_idx")
    assert sum(1 for _ in t) == 1000


@pessoas_available
def test_nome_idx_no_duplicates(t):
    """Each NTX entry must point to a distinct physical record."""
    with NTXReader(str(GERA_DBF / "NOME_IDX.ntx")) as ntx:
        recs = list(ntx)
    assert len(recs) == len(set(recs)) == 1000


@pessoas_available
def test_nome_idx_first_ten_clipper(t):
    """
    Exact match for first 10 rows from resultado_teste.txt:

      Adriana  Braga        21  N
      Adriana  Esteves      21  N
      Adriana  Duarte       21  S
      Adriana  Bittencourt  31  S
      Adriana  Braga        33  S
      Adriana  Araujo       50  N
      Adriana  Souza        56  S
      Adriana  Abreu        58  S
      Adriana  Dantas       62  S
      Adriana  Castro       77  N
    """
    expected = [
        ("Adriana", "Braga",       21, False),
        ("Adriana", "Esteves",     21, False),
        ("Adriana", "Duarte",      21, True),
        ("Adriana", "Bittencourt", 31, True),
        ("Adriana", "Braga",       33, True),
        ("Adriana", "Araujo",      50, False),
        ("Adriana", "Souza",       56, True),
        ("Adriana", "Abreu",       58, True),
        ("Adriana", "Dantas",      62, True),
        ("Adriana", "Castro",      77, False),
    ]
    t.set_order("nome_idx")
    actual = []
    rec = t.go_top()
    for _ in range(10):
        assert rec is not None
        actual.append((_nome(rec), _sob(rec), rec["IDADE"], rec["CASADO"]))
        rec = t._active_ntx.next_rec()
        if rec is not None:
            rec = t.dbf.record(rec)

    assert actual == expected


@pessoas_available
def test_nome_idx_sorted_order(t):
    """All records come out in non-decreasing composite-key order."""
    t.set_order("nome_idx")
    prev_key = None
    for rec in t:
        nome = rec["NOME"]  # 30 chars, already padded
        casado_char = "S" if rec["CASADO"] else "N"
        key = nome + f"{rec['IDADE']:3d}" + casado_char
        if prev_key is not None:
            assert key >= prev_key, f"Out of order: {prev_key!r} > {key!r}"
        prev_key = key


@pessoas_available
def test_nome_idx_seek_adriana_recno(t):
    """
    Clipper result:
      SEEK 'Adriana' -> ENCONTRADO - Adriana Braga  IDADE=21  CAS=N  RECNO=682
    """
    t.set_order("nome_idx")
    # In Clipper, cBusca = NOME (30 chars). We pad to key_size=34 with spaces.
    # The softseek lands on the first composite key >= "Adriana" + spaces.
    rec = t.seek("Adriana", softseek=True)
    assert rec is not None
    assert _nome(rec) == "Adriana"
    assert rec["IDADE"] == 21
    assert rec["CASADO"] is False       # CAS=N
    assert rec["_recno"] == 682
    assert _sob(rec) == "Braga"


@pessoas_available
def test_nome_idx_first_record_is_adriana(t):
    t.set_order("nome_idx")
    rec = t.go_top()
    assert _nome(rec) == "Adriana"


@pessoas_available
def test_nome_idx_all_adriana_before_alberto(t):
    """After all Adrianas the next different name must be lexicographically > 'Adriana'."""
    t.set_order("nome_idx")
    rec = t.seek("Adriana", softseek=True)
    while rec and _nome(rec) == "Adriana":
        nr = t._active_ntx.next_rec()
        rec = t.dbf.record(nr) if nr else None
    if rec:
        assert _nome(rec) > "Adriana"


# ===========================================================================
# TESTE 2 – NASC_IDX  (DTOS(DT_NASC) → "YYYYMMDD", 8-char key)
# ===========================================================================

@pessoas_available
def test_nasc_idx_key_expr(t):
    t.set_order("nasc_idx")
    assert t._active_ntx.key_expr == "DTOS(DT_NASC)"
    assert t._active_ntx.key_size == 8


@pessoas_available
def test_nasc_idx_total_count(t):
    t.set_order("nasc_idx")
    assert sum(1 for _ in t) == 1000


@pessoas_available
def test_nasc_idx_no_duplicates(t):
    with NTXReader(str(GERA_DBF / "NASC_IDX.ntx")) as ntx:
        recs = list(ntx)
    assert len(set(recs)) == 1000


@pessoas_available
def test_nasc_idx_sorted_order(t):
    t.set_order("nasc_idx")
    prev = None
    for rec in t:
        d = rec["DT_NASC"]
        if prev:
            assert d >= prev
        prev = d


@pessoas_available
def test_nasc_idx_five_oldest(t):
    """
    Clipper go_top + 4 skips:
      Livia    Galvao   30/01/1939
      Viviane  Benicio  26/02/1939
      Emerson  Moraes   03/05/1939
      Iolanda  Martins  11/05/1939
      Evandro  Costa    15/05/1939
    """
    expected = [
        ("Livia",   "Galvao",  date(1939,  1, 30)),
        ("Viviane", "Benicio", date(1939,  2, 26)),
        ("Emerson", "Moraes",  date(1939,  5,  3)),
        ("Iolanda", "Martins", date(1939,  5, 11)),
        ("Evandro", "Costa",   date(1939,  5, 15)),
    ]
    t.set_order("nasc_idx")
    rec = t.go_top()
    actual = []
    for _ in range(5):
        assert rec is not None
        actual.append((_nome(rec), _sob(rec), rec["DT_NASC"]))
        nr = t._active_ntx.next_rec()
        rec = t.dbf.record(nr) if nr else None
    assert actual == expected


@pessoas_available
def test_nasc_idx_five_youngest(t):
    """
    Clipper go_bottom + 4 skip(-1) then reversed:
      Sabrina    Martins   26/07/2008
      Cristiano  Esteves   30/07/2008
      Felipe     Fogaca    05/08/2008
      Henrique   Rezende   06/11/2008
      Fernando   Araujo    15/12/2008
    """
    expected_reversed = [
        ("Fernando", "Araujo",  date(2008, 12, 15)),
        ("Henrique", "Rezende", date(2008, 11,  6)),
        ("Felipe",   "Fogaca",  date(2008,  8,  5)),
        ("Cristiano","Esteves", date(2008,  7, 30)),
        ("Sabrina",  "Martins", date(2008,  7, 26)),
    ]
    # Go to last 5 by reading last 5 from iteration (go_bottom not directly usable
    # for "previous 5" without a prev_rec(), so we collect last 5 during iteration)
    t.set_order("nasc_idx")
    tail = []
    for rec in t:
        tail.append((_nome(rec), _sob(rec), rec["DT_NASC"]))
    last5 = tail[-5:]

    # The Clipper output shows them in reverse order (SKIP -1 from bottom),
    # then reverses the array before printing — net result is ascending order.
    # So last5 (ascending) == expected_reversed reversed.
    assert last5 == list(reversed(expected_reversed))


@pessoas_available
def test_nasc_idx_records_since_1990(t):
    """
    Clipper used SEEK DTOS(dFiltro) without SOFTSEEK, found exact=0.
    Our softseek must find all records with DT_NASC >= 1990-01-01.
    Previously confirmed: 274 records.
    """
    t.set_order("nasc_idx")
    count = sum(1 for _ in t.records_since(date(1990, 1, 1)))
    assert count == 274


@pessoas_available
def test_nasc_idx_records_since_all_gte(t):
    t.set_order("nasc_idx")
    cutoff = date(1990, 1, 1)
    for rec in t.records_since(cutoff):
        assert rec["DT_NASC"] >= cutoff


@pessoas_available
def test_nasc_idx_records_before_1990(t):
    """Complement: records with DT_NASC < 1990 = 1000 - 274 = 726."""
    t.set_order("nasc_idx")
    count = sum(1 for rec in t if rec["DT_NASC"] < date(1990, 1, 1))
    assert count == 726


# ===========================================================================
# TESTE 3 – IDADE_IDX  (STR(IDADE,3) → " 18".." 87", 3-char key)
# ===========================================================================

@pessoas_available
def test_idade_idx_key_expr(t):
    t.set_order("idade_idx")
    assert t._active_ntx.key_expr == "STR(IDADE,3)"
    assert t._active_ntx.key_size == 3


@pessoas_available
def test_idade_idx_total_count(t):
    t.set_order("idade_idx")
    assert sum(1 for _ in t) == 1000


@pessoas_available
def test_idade_idx_no_duplicates(t):
    with NTXReader(str(GERA_DBF / "IDADE_IDX.ntx")) as ntx:
        recs = list(ntx)
    assert len(set(recs)) == 1000


@pessoas_available
def test_idade_idx_sorted_order(t):
    """Ages come out non-decreasing."""
    t.set_order("idade_idx")
    prev = None
    for rec in t:
        if prev is not None:
            assert rec["IDADE"] >= prev
        prev = rec["IDADE"]


@pessoas_available
def test_idade_idx_ten_youngest_all_18(t):
    """
    Clipper first 10: all IDADE=18
      Sabrina, Fernando, Felipe, Emerson, Cristiano,
      Renata, Vanessa, Pedro, Viviane, Sabrina
    """
    expected_names = [
        "Sabrina", "Fernando", "Felipe", "Emerson", "Cristiano",
        "Renata",  "Vanessa",  "Pedro",  "Viviane", "Sabrina",
    ]
    t.set_order("idade_idx")
    rec = t.go_top()
    actual = []
    for _ in range(10):
        assert rec is not None
        assert rec["IDADE"] == 18, f"Expected 18, got {rec['IDADE']}"
        actual.append(_nome(rec))
        nr = t._active_ntx.next_rec()
        rec = t.dbf.record(nr) if nr else None
    assert actual == expected_names


@pessoas_available
def test_idade_idx_distribution(t):
    """
    Clipper distribution:
      18-29 : 173
      30-49 : 275
      50-64 : 215
      65+   : 337
    """
    t.set_order("idade_idx")
    f1 = f2 = f3 = f4 = 0
    for rec in t:
        age = rec["IDADE"]
        if age < 30:
            f1 += 1
        elif age < 50:
            f2 += 1
        elif age < 65:
            f3 += 1
        else:
            f4 += 1
    assert f1 == 173, f"18-29: expected 173, got {f1}"
    assert f2 == 275, f"30-49: expected 275, got {f2}"
    assert f3 == 215, f"50-64: expected 215, got {f3}"
    assert f4 == 337, f"65+:   expected 337, got {f4}"


@pessoas_available
def test_idade_idx_seek_40_count(t):
    """
    Clipper: SEEK STR(40,3)  ->  18 registros com IDADE=40.
    STR(40,3) = " 40" (space-padded to 3 chars).
    """
    t.set_order("idade_idx")
    # Pass the exact string that STR(40,3) produces in Clipper: " 40"
    rec = t.seek(" 40", softseek=False)
    assert rec is not None, "SEEK ' 40' should find at least one record"
    count = 0
    while rec is not None and rec["IDADE"] == 40:
        count += 1
        nr = t._active_ntx.next_rec()
        rec = t.dbf.record(nr) if nr else None
    assert count == 18, f"Expected 18 records with IDADE=40, got {count}"


@pessoas_available
def test_idade_idx_seek_nonexistent_age(t):
    """There are no records with IDADE outside 18..87."""
    t.set_order("idade_idx")
    assert t.seek(" 10", softseek=False) is None
    assert t.seek(" 99", softseek=False) is None


@pessoas_available
def test_idade_idx_softseek_boundary(t):
    """softseek ' 40' must land on first record with IDADE >= 40."""
    t.set_order("idade_idx")
    rec = t.seek(" 40", softseek=True)
    assert rec is not None
    assert rec["IDADE"] >= 40


@pessoas_available
def test_idade_idx_distribution_sums_to_1000(t):
    t.set_order("idade_idx")
    counts = Counter(rec["IDADE"] for rec in t)
    assert sum(counts.values()) == 1000


# ===========================================================================
# TESTE 4 – CASADO_IDX  (IF(CASADO,"S","N") → 1-char, N=solteiro, S=casado)
# ===========================================================================

@pessoas_available
def test_casado_idx_key_expr(t):
    t.set_order("casado_idx")
    assert t._active_ntx.key_expr == 'IF(CASADO,"S","N")'
    assert t._active_ntx.key_size == 1


@pessoas_available
def test_casado_idx_total_count(t):
    t.set_order("casado_idx")
    assert sum(1 for _ in t) == 1000


@pessoas_available
def test_casado_idx_no_duplicates(t):
    with NTXReader(str(GERA_DBF / "CASADO_IDX.ntx")) as ntx:
        recs = list(ntx)
    assert len(set(recs)) == 1000


@pessoas_available
def test_casado_idx_distribution(t):
    """
    Clipper:
      Solteiros (N) : 498
      Casados   (S) : 502
    """
    t.set_order("casado_idx")
    solteiros = sum(1 for rec in t if not rec["CASADO"])
    casados   = sum(1 for rec in t if     rec["CASADO"])
    assert solteiros == 498, f"Solteiros: expected 498, got {solteiros}"
    assert casados   == 502, f"Casados:   expected 502, got {casados}"


@pessoas_available
def test_casado_idx_n_before_s(t):
    """'N' (78) < 'S' (83) in ASCII, so solteiros come first."""
    t.set_order("casado_idx")
    recs = list(t)
    casados_pos = [i for i, r in enumerate(recs) if r["CASADO"]]
    solteiros_pos = [i for i, r in enumerate(recs) if not r["CASADO"]]
    assert max(solteiros_pos) < min(casados_pos), \
        "All solteiros must appear before all casados"


@pessoas_available
def test_casado_idx_seek_S_first_five(t):
    """
    Clipper primeiros 5 casados (SEEK 'S'):
      Eunice    Guimaraes
      Fernanda  Fernandes
      Manuela   Duarte
      Vera      Gomes
      Bruno     Brito
    """
    expected = [
        ("Eunice",   "Guimaraes"),
        ("Fernanda", "Fernandes"),
        ("Manuela",  "Duarte"),
        ("Vera",     "Gomes"),
        ("Bruno",    "Brito"),
    ]
    t.set_order("casado_idx")
    rec = t.seek("S", softseek=False)
    actual = []
    for _ in range(5):
        assert rec is not None
        assert rec["CASADO"] is True
        actual.append((_nome(rec), _sob(rec)))
        nr = t._active_ntx.next_rec()
        rec = t.dbf.record(nr) if nr else None
    assert actual == expected


@pessoas_available
def test_casado_idx_seek_N_first_five(t):
    """
    Clipper primeiros 5 solteiros (SEEK 'N'):
      Rebeca   Leite
      Alice    Ulhoa
      Monique  Almeida
      Luana    Kahler
      Paulo    Almeida
    """
    expected = [
        ("Rebeca",  "Leite"),
        ("Alice",   "Ulhoa"),
        ("Monique", "Almeida"),
        ("Luana",   "Kahler"),
        ("Paulo",   "Almeida"),
    ]
    t.set_order("casado_idx")
    rec = t.seek("N", softseek=False)
    actual = []
    for _ in range(5):
        assert rec is not None
        assert rec["CASADO"] is False
        actual.append((_nome(rec), _sob(rec)))
        nr = t._active_ntx.next_rec()
        rec = t.dbf.record(nr) if nr else None
    assert actual == expected


@pessoas_available
def test_casado_idx_after_all_N_comes_S(t):
    """After the last solteiro, the next record must be casado."""
    t.set_order("casado_idx")
    rec = t.seek("N", softseek=False)
    prev = None
    while rec and not rec["CASADO"]:
        prev = rec
        nr = t._active_ntx.next_rec()
        rec = t.dbf.record(nr) if nr else None
    assert prev is not None
    if rec:
        assert rec["CASADO"] is True


# ===========================================================================
# CROSS-INDEX VALIDATION
# ===========================================================================

@pessoas_available
def test_all_indexes_same_total(t):
    """Every index must yield exactly 1000 distinct records."""
    for order in ("nome_idx", "nasc_idx", "idade_idx", "casado_idx"):
        t.set_order(order)
        recs = list(t)
        assert len(recs) == 1000, f"{order}: expected 1000, got {len(recs)}"


@pessoas_available
def test_all_indexes_same_set_of_recnos(t):
    """The set of physical records reached via any index must be identical."""
    sets = {}
    for order in ("nome_idx", "nasc_idx", "idade_idx", "casado_idx"):
        t.set_order(order)
        sets[order] = {rec["_recno"] for rec in t}
    base = sets["nome_idx"]
    for order, s in sets.items():
        assert s == base, f"{order} recno set differs from nome_idx"


@pessoas_available
def test_casado_distribution_cross_check(t):
    """Casado counts from CASADO_IDX must match a direct DBF scan."""
    t.set_order("casado_idx")
    via_idx = Counter("S" if r["CASADO"] else "N" for r in t)

    t.set_order(0)
    via_dbf = Counter("S" if r["CASADO"] else "N" for r in t)

    assert via_idx == via_dbf


@pessoas_available
def test_age_distribution_cross_check(t):
    """Age distribution via IDADE_IDX must match a direct DBF scan."""
    def bucket(age):
        if age < 30: return "18-29"
        if age < 50: return "30-49"
        if age < 65: return "50-64"
        return "65+"

    t.set_order("idade_idx")
    via_idx = Counter(bucket(r["IDADE"]) for r in t)

    t.set_order(0)
    via_dbf = Counter(bucket(r["IDADE"]) for r in t)

    assert via_idx == via_dbf
